### PR TITLE
MeteorFlux and ReactiveState available on the server

### PR DESCRIPTION
**Pull request by fermuch**
See issue #40 for discussion.

### CODE REVIEW

**Comment by fermuch** [comment]
I do have `peerlibrary:reactive-publish` on the app where I need this, and reactive-publish adds Tracker on the server IIRC, but check out the tests. They're also executing on the server without any failure. I'll create a new app from zero just to test if everything is working.

**Comment by fermuch** [comment]
```
meteor create foobar
[...]
➜ cp -r ~/Documentos/Dev/Git/meteorflux/packages/* packages/
➜ meteor add meteorflux:meteorflux
[...]
➜ meteor shell
> State
{ _NOTSET: undefined,
  _obj: {},
  _deps: { children: {}, dep: { _dependentsById: {} } },
  _beforeChangeCallbacks: [],
  _afterChangeCallbacks: [] }
> State.set('asd', 'dsa')
> State.get('asd')
'dsa'
> typeof Tracker
'object'
> new Tracker.Dependency()
{ _dependentsById: {} }
> typeof Tracker.autorun
'function'
> Tracker.autorun(function(){ console.info( State.get('foo') ) })
```

Everything seems to be working. Is there anything I am missing?

**Comment by luisherranz** [comment]
Yeah, it looks like `Tracker` is defined and working on the server:
https://github.com/meteor/meteor/blob/devel/packages/tracker/package.js

I thought it wasn't. This text is from the https://github.com/peerlibrary/meteor-server-autorun README.md:

> While Meteor does provide Tracker.autorun on the server, it is not officially supported on the server and it has many limitations. For example, it cannot be used with fibers-enabled synchronous (blocking) code. This implementation cooperates nicely with fibers and preserves Meteor environment variables where necessary, allowing you to run any reactive code. Now you can really share the same code between client and server.

Do you want me to merge your PR now or wait until you have tested it further?

**Comment by fermuch** [comment]
It is up to you. I am now using this on an app with SSR and everything is working as expected.
This shouldn't break any app, since the only thing that changed is that now we have State and MeteorFlux defined on the server.

**Comment by Poliuk** [comment]
Great @fermuch! Thanks :+1:

**Comment by luisherranz** [comment]
I will publish a new version in atmosphere. Thanks @fermuch.

**Pull request merged**
